
version: '3'

services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    environment:
      EMQX_NAME: emqx_docker
      EMQX_HOST: 127.0.0.1
    ports:
      - "1883:1883"
      - "8883:8883"
      - "18083:18083"

  mobiusdb:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mobiusdb
      - MYSQL_ROOT_PASSWORD=mysql
      - TZ=Asia/Seoul
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
